### ISSUE TITLE
cmp-buffer-lines breaks LSP

### ISSUE THREAD

**Issue by redve-dev** [amarakon/nvim-cmp-buffer-lines#1]
I have installed cmp-buffer-lines with:
<pre>
use ({"amarakon/nvim-cmp-buffer-lines", config = function()
	require("setup/buffer-lines")
end})
</pre>

setup/buffer-lines.lua looks like:
<pre>
require"cmp".setup {
	sources = {
		{ name = "buffer-lines" }
	}
}
</pre>

LSP servers stop autocomplete your code.
In pyright, it displays errors, and warnings for unused variables, but it doesn't autocomplete the code.
In clangd, it doesn't see functions from STL, and sees cout as an error (despite the fact gcc has no problem to compile it).

Tested with clangd and pyright servers. 
Here is my config: https://github.com/redve-dev/dotfiles/tree/master/nvim/lua
Tested with neovim v0.9.0

**Comment by amarz45** [comment]
> LSP servers stop autocomplete your code.

I think the reason you are no longer seeing LSP autocompletion is that you have `buffer-lines` as the **only** source in the cmp setup. Try something like this:

```lua
require "cmp".setup {
    sources = {
        { name = "nvim_lsp" },
        { name = "buffer-lines" }
    }
}
```

Make sure you also have [lspconfig](https://github.com/neovim/nvim-lspconfig) and [cmp-nvim-lsp](https://github.com/hrsh7th/cmp-nvim-lsp) installed.

> In pyright, it displays errors, and warnings for unused variables, but it doesn't autocomplete the code.

Try what I did above.

> In clangd, it doesn't see functions from STL, and sees cout as an error (despite the fact gcc has no problem to compile it).

Sorry, I do not have experience with programming in C++ so I do not know what that means. Can you please provide me a reproducible example?
