### ISSUE TITLE
[feature request]Show line numbers in the complementary menu of the search command line

### ISSUE THREAD

**Issue by yyy33** [amarakon/nvim-cmp-buffer-lines#3]
![bbb](https://user-images.githubusercontent.com/51548147/201557985-e528e42a-7074-4d01-884b-9b8e3216238e.png)

**Comment by amarz45** [comment]
That's a great idea, I will work on it. For duplicate lines, I might need to show all the line numbers where that line is present.

**Comment by amarz45** [comment]
This feature is available in the latest commit.
