### ISSUE TITLE
How to use this plugin with large files?

### ISSUE THREAD

**Issue by bagohart** [amarakon/nvim-cmp-buffer-lines#6]
This plugin works now, but not for large files.
I don't care if it's not very fast, but it should at least work at all.
I press `<C-x><C-l>` and then nothing happens if the file is large. (2530 lines)
This is my configuration:
```lua
                    ['<C-x><C-l>'] = cmp.mapping.complete({ -- manual ^X^L is broken,↴
                        config = {
                            sources = {
                                { name = 'buffer-lines' },
                                option = {
                                    words = true, -- not sure what this does...
                                    comments = true, -- not sure what this does...
                                    leading_whitespace = true, -- not sure. is stripped on buffer insertion anyway.
                                    max_size = 10000000, -- kB
                                },
                            },
                        },
                    }),
```
This line should govern execution conditional on file size:
```lua
if vim.fn.getfsize(vim.fn.expand("%")) > (opts.max_size * 1000) then
		return
	end
```
and the output of `getfsize(expand("%"))` is `117943`, so the whole expression should evaluate to false.

I also tried to set
```lua
            cmp.setup({
                performance = {
                    fetching_timeout = 100000,
                },
-- ...
```
but it didn't make any difference.

Is there a way to make this work?

**Comment by amarz45** [comment]
Can you upload the file somewhere and send it to me so I can test it myself? Thanks.

**Comment by amarz45** [comment]
Also, you wrote in comments in your code that you're not sure what `words` and `comments` options do. I'll explain them here. If `words` is set to false (the default), lines that are a single word will not be shown. For example:

```
line1 text
line2
```

Only the first line of the above code block will be shown. If `comments` is set to false (the default), comments will be stripped from the results. For example:

```lua
print "Hello world" -- This is a comment
```

The result will be this instead:

```lua
print "Hello world"
```

Lines that are just comments will also be removed.

I should probably update the documentation to make it more clear.

**Comment by bagohart** [comment]
I tried it on my current `init.lua`
https://gist.github.com/bagohart/f59b7941f05ec7b58e0d1b2077cf1f2d
But it happens for other large files, too. (Just copied Faust from Project Gutenberg and tried it with that.)
And I just noticed that if I paste the text into a fresh buffer, then it works. only when I then save that to a file, then it stops working.
So probably this has nothing to do with the specific file.

**Comment by amarz45** [comment]
I am very busy with school right now so sorry if it takes me a while to fix it.

**Comment by amarz45** [comment]
Lol I forgot about this issue until I looked at my email again. I tested it on a file that’s 3534 lines and it worked. The URL for the 2530 line file you provided no longer works. Can you test it again and if it doesn’t work, can you update the URL so that I can test it and fix it?

**Comment by bagohart** [comment]
I don't think it's anything special with that file.
For example, it doesn't work for me with Faust plaintext:
https://gist.github.com/bagohart/803e22ca03d224992e2435820ddbe29f

**Comment by amarz45** [comment]
The file you provided is 194 kB. The `max_size` option is used to define the maximum file size for which nvim-cmp-buffer-lines will work, in kilobytes. The default is `100` for 100 kB. It worked for me when I set it to `200`:

```lua
require "cmp".setup {
    sources = {
        {
            name = "buffer-lines",
            option = { max_size = 200 }
        }
    }
}
```

I’m probably gonna change it so that giving a max size of `0` will make the max size unlimited, for those who don't want to set a maximum file size.

**Comment by bagohart** [comment]
Allowing an unlimited size seems useful. Maybe use `nil` instead of `0`? (I'm not sure if Lua allows this, though.)
And the config you give works for me, too.
But I was already aware of the `max_size` option, as should be obvious from my first post.

So, I looked at this again with fresh eyes and noticed that the real problem was that my config is just broken: It was
```lua
sources = {
                                { name = 'buffer-lines' },
                                option = {
                                    words = true,
                                    comments = true,
                                    leading_whitespace = true,
                                    max_size = 10000000, -- kB
                                },
                            },
```
which is simply structurally wrong >_< since there the option is given as a second source. It should have been:
```lua
sources = {
                                {
                                    name = 'buffer-lines',
                                    option = {
                                        words = false,
                                        comments = true,
                                        leading_whitespace = false,
                                        max_size = 1000000000,
                                    },
                                },
}
```
And with that, it works on the big files just fine...

So I guess that conclusively explains what was going on. Thank you for your testing efforts!

**Comment by amarz45** [comment]
> Allowing an unlimited size seems useful. Maybe use nil instead of 0? (I'm not sure if Lua allows this, though.)

I will try this out.

> So, I looked at this again with fresh eyes and noticed that the real problem was that my config is just broken

Oh, I didn’t realize that. Now I understand why it wasn’t working for you.

> So I guess that conclusively explains what was going on. Thank you for your testing efforts!

You’re welcome. I am going to work on making it possible to set an unlimited maximum file size.
