### ISSUE TITLE
94016bd06ca88379f4fedb7e9004d8783b9628e9 breaks '/' completion

### ISSUE THREAD

**Issue by junkblocker** [amarakon/nvim-cmp-buffer-lines#8]
`/` freezes on completion after 94016bd06ca88379f4fedb7e9004d8783b9628e9 . CPU gets stuck at 100% and can't Ctrl+C out of it. Sending SIGINT or harder to nvim is the only way to kill nvim at that point.

24c6d25dea71276d4fc064a8e6a63f9a3039c96c works just fine.

**Comment by amarz45** [comment]
I can't reproduce it. I tried it and it works fine for me. Can you show me a reproducible example of your configuration?

**Update:** I tried it on a bigger file and I am having the same issue. I will try to solve it as soon as possible. Quick question: do you have tree-sitter installed?

**Comment by amarz45** [comment]
I think I fixed it in the latest commit. Please test it.

**Comment by junkblocker** [comment]
yep, that fixed it. Thank you!
