### ISSUE TITLE
Fails on lines with indentation.

### ISSUE THREAD

**Issue by jihedmastouri** [amarakon/nvim-cmp-buffer-lines#9]
I am trying to use this plugin to replace the default <C-x><C-l>.

In this example, the plugin does not give any suggestions. (This is also my config)
![image](https://user-images.githubusercontent.com/25284659/207223689-3262b253-118b-44e3-b72b-fea61cd77d58.png)

At the beginning of the line, it works like a charm.
![image](https://user-images.githubusercontent.com/25284659/207223940-00a89885-83ea-41a3-ac56-7ad528aef35e.png)

I think It would be better to ignore whitespaces/indetations at the start of the line.

**Comment by amarz45** [comment]
Unfortunately, I do not think this is possible with the way nvim-cmp works. The code that governs the suggestions is this:

```lua
function source.get_keyword_pattern()
	return ".*"
end
```

I can change `".*"` to `"\\\\[^[:blank:]]*"` to make it work on lines with indentation, but that will also mean that you won't be able to complete entries with whitespace in them. If you think I am wrong, and that it is indeed possible to do this, please submit a pull request.

**Comment by tummetott** [comment]
I'm facing the same issue and find it very annoying. Thats I'd love to solve the problem but I don't quite understand the `keyword_patterns`. The README of cmp is also very bad and does not tell me anything. Could you explain me how this `keyword_patterns` are meant to work? I know how lua regexs work, but i don't know against what i'm matching and whats the idea in the first place

**Comment by tummetott** [comment]
Ok I think I get it, never mind. It's first of all not LUA regex but POSIX. And the the regex matches against the longest char sequence before the cursor and compares it to the completion items. Isn't `"[^[:blank:]].*"` a regex that should solve the problem? We simply start at the first non-blank but then everything is allowed (also blanks).
